services:
  redis:
    image: redis
    ports:
    - "6379:6379"
  travelokav2.api:
    image: ${DOCKER_REGISTRY-}travelokav2api
    build:
      context: .
      dockerfile: src/TravelokaV2.API/Dockerfile

